---
- name: create the backup directory
  file: state=directory
        dest='{{ pt_backup_dir }}'
        owner='{{ pt_user }}'

- name: upload the backup script
  template: src='scripts/backup_db.sh.j2'
            dest='{{ pt_backup_dir }}/backup_db.sh'
            owner='{{ pt_user }}' mode=0700
            backup=yes

- name: path for cron jobs
  cronvar: name=PATH
           value='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin'
           user='{{ pt_user }}'

- name: add cron job for backups
  cron: name='Backup DB for PlayTerminal' minute=0 hour=2
        user='{{ pt_user }}'
        job='bash {{ pt_backup_dir }}/backup_db.sh'

# TODO rotation

- name: backup the database
  command: bash '{{ pt_backup_dir }}/backup_db.sh'
  when: pt_backup_db
  become_user: '{{ pt_user }}'
