---
- name: run migrations
  command: '{{ pt_venv }}/bin/python manage.py migrate --noinput'
  args:
    chdir: '{{ pt_repo_dir }}'
  register: pt_migrate
  changed_when: "'No migrations to apply' not in pt_migrate.stdout"
  become_user: '{{ pt_user }}'

- name: collect static
  command: '{{ pt_venv }}/bin/python manage.py collectstatic --noinput'
  args:
    chdir: '{{ pt_repo_dir }}'
  register: pt_collect_static
  changed_when: "'0 static files copied' not in pt_collect_static.stdout"
  become_user: '{{ pt_user }}'

- name: restart application
  command: supervisorctl restart playterminal
