---
- name: Create the iptables directory
  file: path={{ iptables_root }}/iptables
        state=directory

- name: Copy the firewall script
  template: src=iptables/firewall.sh.j2
            dest={{ iptables_root }}/iptables/firewall.sh
            backup=yes
            mode=0700

- name: Copy helper files
  copy: src=iptables/{{ item.file }}
        dest={{ iptables_root }}/iptables/
  with_items:
    - {file: README.txt}

- name: Check that the SSH port won't be blocked by the firewall
  assert:
    that: "{{ ansible_port or 22 }} in {{ iptables_map['tcp']['in']|map(attribute='port')|list }}"

- name: Enable firewall
  command: bash {{ iptables_root }}/iptables/firewall.sh enable
  register: enable_iptables_firewall
  changed_when: "'No changes.' not in enable_iptables_firewall.stdout"
  when: enable_firewall
  tags: security.enable_firewall

- name: Disable firewall
  command: bash {{ iptables_root }}/iptables/firewall.sh disable
  register: disable_iptables_firewall
  changed_when: "'No changes.' not in disable_iptables_firewall.stdout"
  when: disable_firewall
  tags: security.disable_firewall
