---
- name: Install security packages
  apt: name={{ item }} state=present
  with_items:
    - fail2ban             # Bans bruteforce stuff
    - netbase              # Provides /etc/services, required for fail2ban
    - unattended-upgrades  # Automatic updates

- name: Ensure fail2ban is running and enabled on boot
  service: name=fail2ban state=started enabled=yes

- name: Configure automatic security updates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
  when: security_autoupdate_enabled

- name: Install iptables-persistent
  apt: name=iptables-persistent state=present
  notify:
    - remove persistent iptables rules

- name: Include advanced iptables scripts
  include: iptables.yml
  tags: security.iptables
