---
- name: ensure that an outdated 'supervisor' system package is not installed
  apt: name=supervisor state=absent

- name: install pip supervisor packages for debian/ubuntu
  pip: name='{{ item.name }}' version='{{ item.version }}'
       state=present
  with_items:
    - {name: supervisor, version: '3.2.3'}
    - {name: supervisor-wildcards, version: '0.1.3'}

- name: ensure supervisor conf.d and log.d directory exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisor

- name: copy supervisor global configuration
  template: src=supervisord.conf.j2
            dest=/etc/supervisord.conf
            owner=root group=root mode=660
            backup=yes
  notify: reload supervisor

- name: copy supervisor init script
  copy: src=supervisor.init
        dest=/etc/init.d/supervisor
        owner=root group=root mode=755
        backup=yes

- name: enable supervisor service
  service: name=supervisor state=started enabled=yes

- name: force handlers
  meta: flush_handlers
